# -*- coding: utf-8 -*-
{
    'name': 'Codec Website V2',
    'summary': 'Rediseño del website de Codec S.R.L',
    'description': 'Sustituye la home por el nuevo diseño que contiene: header fijo, slider, secciones, planes, footer, modo light/dark y cambio de color primario entre violeta y azul.',
    'version': '18.0.1.0.0',
    'category': 'Website/Theme',
    'author': 'Codec S.R.L - José Marty',
    'website': 'https://www.codec.do',
    'license': 'LGPL-3',
    'depends': ['website', 'website_crm'],
    'data': [
        'views/head.xml',
        'views/header.xml',
        'views/section_hero.xml',
        'views/section_sistema.xml',
        'views/section_nosotros.xml',
        'views/section_video.xml',
        'views/section_servicios.xml',
        'views/section_proceso.xml',
        'views/section_planes.xml',
        'views/section_cta.xml',
        'views/section_contacto.xml',
        'views/footer.xml',
        'views/floating.xml',
        'views/javascript.xml',
        'views/layout.xml',
        'views/home.xml',
    ],
    'installable': True,
    'application': False,
}
